### PR TITLE
React 16.3 support

### PR DESCRIPTION
**Pull request by japgolly**
Everything except ref forwarding which will need some thought

### CODE REVIEW

**Comment by cquiroz** [comment]
This is great, thanks!

**Comment by japgolly** [comment]
You're welcome! :D

**Comment by ngbinh** [comment]
Great, thanks

**Comment by mpartel** [comment]
Thanks!
Any chance of a (pre)release soon?

(I tried a ProjectRef inclusion of the branch but got a weird build error)

**Comment by japgolly** [comment]
Hey @mpartel, yeah I'm back on this again giving it my full (free-time) attention so hopefully a release soon. The last feature #483 (forward refs) is incredibly difficult to implement and causing lots of pain but as soon as I complete that a release will follow very fast.

**Pull request merged**
