### PR TITLE
document interop with thirdparty components

### PR DESCRIPTION
**Pull request by chandu0101**

### CODE REVIEW

**Comment by japgolly** [comment]
Awesome @chandu0101. Will merge this in my next round of doco focus.

**Comment by japgolly** [comment]
Hey @chandu0101 , today @ramnivas just released https://github.com/payalabs/scalajs-react-bridge which does a similar thing using macros - pretty cool.

I'm thinking, instead of merging this it might be better to have some links, a link to your guide (which you can edit at any time without needing a PR), and a link to @ramnivas's new thing, and another other interesting tools. How about we close this you and you choose a stable URL to host this doc?

**Comment by chandu0101** [comment]
that works for me , i'll send a new a PR with my link :)

**Comment by japgolly** [comment]
Cool. Just msg me the link, don't worry about a PR.

**Comment by chandu0101** [comment]
sorry for delay , here is the link : 
https://github.com/chandu0101/scalajs-react-components/blob/master/doc/InteropWithThirdParty.md

**Pull request closed without merging**
