### PR TITLE
Limit max classfile name length to 128 chars

### PR DESCRIPTION
**Pull request by easel**
- Unlimited classfile names were blowing up builds in docker, etc

### CODE REVIEW

**Comment by easel** [comment]
This fail is interesting =/

**Comment by japgolly** [comment]
Ah this one's sneaky. If you set this option, you need EVERYTHING on your classpath to have been compiled with the same option and value, or else you get **runtime** bugs. ([Source](http://scala-language.1934581.n4.nabble.com/Xmax-classfile-name-td4637574.html))

**Comment by easel** [comment]
That's pretty fail. I'll see if I can figure out which classfile(s) are getting such long names.

**Comment by easel** [comment]
Well the longest two file names are these, at 303 characters total. Not entirely sure how to cut them down though...

303 ./extra/scala-2.11/classes/japgolly/scalajs/react/extra/Px$$anonfun$apply15$1$$anonfun$apply$92$$anonfun$apply$93$$anonfun$apply$94$$anonfun$apply$95$$anonfun$apply$96$$anonfun$apply$97$$anon
fun$apply$98$$anonfun$apply$99$$anonfun$apply$100$$anonfun$apply$101$$anonfun$apply$102$$anonfun$apply$103.sjsir
303 ./extra/scala-2.11/classes/japgolly/scalajs/react/extra/Px$$anonfun$apply15$1$$anonfun$apply$92$$anonfun$apply$93$$anonfun$apply$94$$anonfun$apply$95$$anonfun$apply$96$$anonfun$apply$97$$anon
fun$apply$98$$anonfun$apply$99$$anonfun$apply$100$$anonfun$apply$101$$anonfun$apply$102$$anonfun$apply$103.class

**Comment by easel** [comment]
Here's a reference to the upstream issue: https://github.com/hseeberger/scala-sbt/issues/3

**Comment by japgolly** [comment]
Haha wow, that's huge. Maybe we could get a list of classes > 240 chars and refactor them?

**Comment by easel** [comment]
I believe this is everything:

```
249 ./Px$$anonfun$apply15$1$$anonfun$apply$92$$anonfun$apply$93$$anonfun$apply$94$$anonfun$apply$95$$anonfun$apply$96$$anonfun$apply$97$$anonfun$apply$98$$anonfun$apply$99$$anonfun$apply$100$$anonfun$apply$101$$anonfun$apply$102$$anonfun$apply$103.sjsir
249 ./Px$$anonfun$apply15$1$$anonfun$apply$92$$anonfun$apply$93$$anonfun$apply$94$$anonfun$apply$95$$anonfun$apply$96$$anonfun$apply$97$$anonfun$apply$98$$anonfun$apply$99$$anonfun$apply$100$$anonfun$apply$101$$anonfun$apply$102$$anonfun$apply$103.class
246 ./Px$$anonfun$apply21$1$$anonfun$apply$191$$anonfun$apply$192$$$$$$9052638afa333fc0ea9135b839aa9ceb$$$$$199$$anonfun$apply$200$$anonfun$apply$201$$anonfun$apply$202$$anonfun$apply$203$$anonfun$apply$204$$anonfun$apply$205$$anonfun$apply$206.sjsir
246 ./Px$$anonfun$apply21$1$$anonfun$apply$191$$anonfun$apply$192$$$$$$9052638afa333fc0ea9135b839aa9ceb$$$$$199$$anonfun$apply$200$$anonfun$apply$201$$anonfun$apply$202$$anonfun$apply$203$$anonfun$apply$204$$anonfun$apply$205$$anonfun$apply$206.class
246 ./Px$$anonfun$apply18$1$$anonfun$apply$137$$anonfun$apply$138$$$$$$b5747acc6784a01d93d99a77a2d32277$$$$$145$$anonfun$apply$146$$anonfun$apply$147$$anonfun$apply$148$$anonfun$apply$149$$anonfun$apply$150$$anonfun$apply$151$$anonfun$apply$152.sjsir
246 ./Px$$anonfun$apply18$1$$anonfun$apply$137$$anonfun$apply$138$$$$$$b5747acc6784a01d93d99a77a2d32277$$$$$145$$anonfun$apply$146$$anonfun$apply$147$$anonfun$apply$148$$anonfun$apply$149$$anonfun$apply$150$$anonfun$apply$151$$anonfun$apply$152.class
246 ./Px$$anonfun$apply17$1$$anonfun$apply$121$$anonfun$apply$122$$$$$$38d1333430beefa34e2649b173f0c19a$$$$$129$$anonfun$apply$130$$anonfun$apply$131$$anonfun$apply$132$$anonfun$apply$133$$anonfun$apply$134$$anonfun$apply$135$$anonfun$apply$136.class
245 ./Px$$anonfun$apply22$1$$anonfun$apply$211$$anonfun$apply$212$$$$$$6f4e30a5ef95d99f9eb3d4a543f9c97$$$$$219$$anonfun$apply$220$$anonfun$apply$221$$anonfun$apply$222$$anonfun$apply$223$$anonfun$apply$224$$anonfun$apply$225$$anonfun$apply$226.sjsir
245 ./Px$$anonfun$apply22$1$$anonfun$apply$211$$anonfun$apply$212$$$$$$6f4e30a5ef95d99f9eb3d4a543f9c97$$$$$219$$anonfun$apply$220$$anonfun$apply$221$$anonfun$apply$222$$anonfun$apply$223$$anonfun$apply$224$$anonfun$apply$225$$anonfun$apply$226.class
245 ./Px$$anonfun$apply20$1$$anonfun$apply$172$$anonfun$apply$173$$$$$$c746f91e3eb9cd660e4b1357aa85efb$$$$$180$$anonfun$apply$181$$anonfun$apply$182$$anonfun$apply$183$$anonfun$apply$184$$anonfun$apply$185$$anonfun$apply$186$$anonfun$apply$187.sjsir
245 ./Px$$anonfun$apply20$1$$anonfun$apply$172$$anonfun$apply$173$$$$$$c746f91e3eb9cd660e4b1357aa85efb$$$$$180$$anonfun$apply$181$$anonfun$apply$182$$anonfun$apply$183$$anonfun$apply$184$$anonfun$apply$185$$anonfun$apply$186$$anonfun$apply$187.class
245 ./Px$$anonfun$apply14$1$$anonfun$apply$79$$anonfun$apply$80$$anonfun$apply$81$$anonfun$apply$82$$anonfun$apply$83$$anonfun$apply$84$$anonfun$apply$85$$anonfun$apply$86$$anonfun$apply$87$$anonfun$apply$88$$anonfun$apply$89$$anonfun$apply$90.sjsir
245 ./Px$$anonfun$apply14$1$$anonfun$apply$79$$anonfun$apply$80$$anonfun$apply$81$$anonfun$apply$82$$anonfun$apply$83$$anonfun$apply$84$$anonfun$apply$85$$anonfun$apply$86$$anonfun$apply$87$$anonfun$apply$88$$anonfun$apply$89$$anonfun$apply$90.class
245 ./Px$$anonfun$apply13$1$$anonfun$apply$67$$anonfun$apply$68$$anonfun$apply$69$$anonfun$apply$70$$anonfun$apply$71$$anonfun$apply$72$$anonfun$apply$73$$anonfun$apply$74$$anonfun$apply$75$$anonfun$apply$76$$anonfun$apply$77$$anonfun$apply$78.class
244 ./Px$$anonfun$apply22$1$$anonfun$apply$211$$anonfun$apply$212$$$$$$959282d66eb698f41d5a25f71c404a$$$$$224$$anonfun$apply$225$$anonfun$apply$226$$anonfun$apply$227$$anonfun$apply$228$$anonfun$apply$229$$anonfun$apply$230$$anonfun$apply$231.class
244 ./Px$$anonfun$apply19$1$$anonfun$apply$154$$anonfun$apply$155$$$$$$fbfe35bbc67163d348685c0d31d493$$$$$162$$anonfun$apply$163$$anonfun$apply$164$$anonfun$apply$165$$anonfun$apply$166$$anonfun$apply$167$$anonfun$apply$168$$anonfun$apply$169.sjsir
244 ./Px$$anonfun$apply19$1$$anonfun$apply$154$$anonfun$apply$155$$$$$$fbfe35bbc67163d348685c0d31d493$$$$$162$$anonfun$apply$163$$anonfun$apply$164$$anonfun$apply$165$$anonfun$apply$166$$anonfun$apply$167$$anonfun$apply$168$$anonfun$apply$169.class
238 ./Px$$anonfun$apply22$1$$anonfun$apply$211$$anonfun$apply$212$$anonfun$apply$213$$anonfun$apply$214$$anonfun$apply$215$$anonfun$apply$216$$anonfun$apply$217$$anonfun$apply$218$$anonfun$apply$219$$anonfun$apply$220$$anonfun$apply$221.sjsir
238 ./Px$$anonfun$apply22$1$$anonfun$apply$211$$anonfun$apply$212$$anonfun$apply$213$$anonfun$apply$214$$anonfun$apply$215$$anonfun$apply$216$$anonfun$apply$217$$anonfun$apply$218$$anonfun$apply$219$$anonfun$apply$220$$anonfun$apply$221.class

**Comment by easel** [comment]
I'm going to take a flyer and guess the offending bit is the generated constructors like https://github.com/japgolly/scalajs-react/blob/master/extra/src/main/scala/japgolly/scalajs/react/extra/Px.scala#L341

**Comment by easel** [comment]
Ok cutting out apply13-apply22 brings the maximum class file names to these:

```
227 ./Px$$anonfun$apply12$1$$anonfun$apply$56$$anonfun$apply$57$$anonfun$apply$58$$anonfun$apply$59$$anonfun$apply$60$$anonfun$apply$61$$anonfun$apply$62$$anonfun$apply$63$$anonfun$apply$64$$anonfun$apply$65$$anonfun$apply$66.class
209 ./Px$$anonfun$apply12$1$$anonfun$apply$56$$anonfun$apply$57$$anonfun$apply$58$$anonfun$apply$59$$anonfun$apply$60$$anonfun$apply$61$$anonfun$apply$62$$anonfun$apply$63$$anonfun$apply$64$$anonfun$apply$65.sjsir
209 ./Px$$anonfun$apply12$1$$anonfun$apply$56$$anonfun$apply$57$$anonfun$apply$58$$anonfun$apply$59$$anonfun$apply$60$$anonfun$apply$61$$anonfun$apply$62$$anonfun$apply$63$$anonfun$apply$64$$anonfun$apply$65.class
209 ./Px$$anonfun$apply11$1$$anonfun$apply$46$$anonfun$apply$47$$anonfun$apply$48$$anonfun$apply$49$$anonfun$apply$50$$anonfun$apply$51$$anonfun$apply$52$$anonfun$apply$53$$anonfun$apply$54$$anonfun$apply$55.class
```

So the issue is those deep for comprehensions are desuraging to .flatMap{.flatMap{.flatMap and each one is an anonymous function that affects the class name. Trying to think of the best approach to refactor to avoid the nesting....

**Comment by easel** [comment]
So it seems like the solution here is to unroll the for comprehension, something like this:
```
    @inline def apply3[A,B,C,Z](pa:Px[A], pb:Px[B], pc:Px[C])(z:(A,B,C)⇒Z): Px[Z] = {
      // for {a←pa;b←pb;c←pc} yield z(a,b,c)
      def da(b: B, c: C): Derivative[Z] = pa.map(a => z(a, b, c))
      def db(c: C): Derivative[Z] = pb.flatMap(b => da(b, c))
      pc.flatMap(db)
   }
```

@japgolly Thoughts on the change? It's a lot more verbose but it would be generated code and should have the same performance characteristics.

As an aside, I asked on the scala channel and apparently this problem goes away on 2.12 due to the native jdk8 anonymous function support.

**Comment by japgolly** [comment]
@easel I don't mind it being a bit more verbose because it is generated as you say. There should probably be a comment in there justifying the verbosity though.

I would like to confirm that the performance is the same. I don't know how those inner functions will be handled by the optimiser. I have assumptions but it would be good to verify. Maybe a comparison of the before/after `fullOptJS` output? What do you think?

Also glad to hear this will go away with Scala 2.12 :)

**Comment by easel** [comment]
As long as you're good with it in principle I'll finish up the changes to gen-px and we can kick it around a bit. Thanks

**Comment by japgolly** [comment]
Hey @easel, this PR isn't ready so I'm going to close it for now. Feel free to submit a new one later or I can reopen this if you like. Cheers

**Comment by easel** [comment]
Sounds good. I'm actually trying to get a concrete fix for this into scala 2.12, but I'm not real optimistic it's going to happen.

**Comment by japgolly** [comment]
That sucks. So what does this mean for you? Is this preventing you from using Docker? Have you sidestepped this somehow?

**Comment by easel** [comment]
Well, I'm avoiding the problem right now by not compiling scalajs-react as part of my build. This is ok since all my upstream stuff has now been merged and I can the build straight from maven central =p

I did make a start at updating the genpx script to avoid all the nested closures but it's not done yet, nor tested, so lets see if the issue raises itself again or goes away magically with time =p

**Pull request closed without merging**
