### PR TITLE
Change jquery call to use jQuery, not the Dynamic.global

### PR DESCRIPTION
**Pull request by ericssmith**
Code doesn't run as is. Changed to use jQuery.

### CODE REVIEW

**Comment by japgolly** [comment]
@chandu0101 ?

**Comment by chandu0101** [comment]
hmm ..
```js
<script>
    function jsonp(url, callback) {
        var callbackName = 'jsonp_callback_' + Math.round(100000 * Math.random());
        window[callbackName] = function(data) {
            delete window[callbackName];
//            document.body.removeChild(script);
            callback(data);
        };
        var script = document.createElement('script');
        script.src = url + (url.indexOf('?') >= 0 ? '&' : '?') + 'callback=' + callbackName;
        document.body.appendChild(script);
    }
</script>
```

in gh-pages we have this in index.html , only for jsonp i didn't feel like adding library dependency at that time! ,feel free to change :)

**Comment by japgolly** [comment]
Ah ok, I understand this a bit more now.

Hmmm, ok I think what we should do is move this jsonp method out of JS in index.html into a Scala.JS function and then put it in the PictureExample with a note that JQuery provides it too.

Or something similar to that. Pretty much exactly what you said @chandu0101 except not adding it as part of scalajs-react itself, just part of the example. And if that's what you already meant (I just reread and it could go either way) then I agree :D Clearly I'm a little tired right noww. :P

**Comment by japgolly** [comment]
Thanks for this PR but #320 will supersede this.

**Pull request closed without merging**
