### PR TITLE
change return type of isMounted()

### PR DESCRIPTION
**Pull request by chandu0101**
i just got this error 

```scala
Uncaught scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: undefined is not an instance of java.lang.Boolean
```

when calling isMounted()

### CODE REVIEW

**Comment by japgolly** [comment]
What did you get it on? Did you manually cast anything before getting the result?

**Comment by chandu0101** [comment]
no i am just doing if(node.isMounted() )

**Comment by japgolly** [comment]
node comes from where?

**Comment by chandu0101** [comment]
selectedNode : BackendScope[NodeProps,NodeState]

i am house keeping scopes in my component when ever there is a change! ,i have to dig more to se what exactly i am doing , i wrote this code 6 months back :) 

nevertheless any issues if we have UndefOr[Boolean] ?  and btw i am using react 0.13.3

**Comment by japgolly** [comment]
I don't want to fix this before we understand exactly what fix needs to be, we should recreate it in a test first. Maybe fix is to remove a trait so `isMounted` isn't available, or even rename & hide & add facade. Too soon to tell. But I don't want `isMounted` return type to have 3 possible values - should be 2.

**Comment by chandu0101** [comment]
that makes sense , let me see if i can reproduce with a test case :)

**Comment by chandu0101** [comment]
as i suspected this is happening in reactjs 0.13.x

here is test case 

```scala
 var cache : BackendScope[_,_] = null
      class Backend(t : BackendScope[_,_]) {
        def cacheScope() = cache = t
      }
      val C = ReactComponentB[Unit]("ChildComp")
        .stateless
        .backend(new Backend(_))
        .render(P => div())
        .componentWillMount(scope => assert(!scope.isMounted()))
        .componentDidMount(scope => scope.backend.cacheScope())
        .buildU

      case class State(toggle : Boolean = true)

      val P = ReactComponentB[Unit]("ParentComp")
        .initialState(State())
        .noBackend
        .render((P,S,B) =>
          div(
            S.toggle ?= C()
          )
        )
        .componentDidMount(scope => {
        assert(cache.isMounted()) // test cached scope also
        scope.modState(s => s.copy(toggle = !s.toggle))
      })
        .buildU

      val instance =  ReactTestUtils.renderIntoDocument(P())

      assert(!cache.isMounted()) // check after child mounted

```

**Comment by japgolly** [comment]
This ↓ can never return `undefined` right?
```js
return (
  internalInstance &&
  internalInstance !== ReactLifeCycle.currentlyMountingInstance
);
```

The comment on that fn seems to support my supposition that I'm not crazy and JS isn't *that* crazy. How can that function above result in `undefined is not an instance of java.lang.Boolean` for us?

**Comment by chandu0101** [comment]
u r not , but JS is :p 

```js
// try thisin console
undefined&&true
= undefined in console 
```

**Comment by japgolly** [comment]
Seriously wtf is wrong with JS???
```js
> undefined && true
undefined

> undefined && false
undefined

> true && undefined
undefined

> false && undefined
false
```

Awesome that you tracked this down. It looks like a React bug to me. If you you raise over there they'll probably fix it pretty quickly.

**Comment by chandu0101** [comment]
ah its fixed already https://github.com/facebook/react/issues/3814 

will be in next version of react :)

**Comment by japgolly** [comment]
excellent

**Pull request closed without merging**
