### PR TITLE
Adding link to Scaladoc in README.md

### PR DESCRIPTION
**Pull request by jhegedus42**

### CODE REVIEW

**Comment by japgolly** [comment]
First of all, AWESOME! I didn't know it was publicly, freely and automatically hosted.
Second, the reason I haven't merged this is because I want to add links to the ScalaDoc of each module, not just the `core` module. I think I didn't reply because I was thinking it would be easier to do it myself with formatting the way I want rather than ask you and then keep bike-shedding replies, making you (rightfully) annoyed. Anyway, ran out of time and forgot, won't have time until Feb. It's a bit menial but feel free to update the PR, else I'll leave this outstanding for another few weeks.

**Comment by jhegedus42** [comment]
No rush, it's good to know that Scaladoc exists :)

**Comment by japgolly** [comment]
Cool, merged and updated in 50cda2e03d567f01ef19280af172936d4ac06bc3. Thanks @jhegedus42

**Comment by jhegedus42** [comment]
Happy to contribute if I can.

**Pull request merged**
