### PR TITLE
generalize tryFocus to tryTo

### PR DESCRIPTION
**Pull request by MasseGuillaume**
for example someRef(scope).tryTo(_.scrollIntoView())

### CODE REVIEW

**Comment by japgolly** [comment]
Hi @MasseGuillaume. Two small things:

1. Implementation looks good to me. Just a note on style though, could you please make the return types explicit and put the implementation on a different line than the signature?

2. Could you please add a quick mention in the changelog.

**Comment by MasseGuillaume** [comment]
@japgolly done squashed changes

**Comment by MasseGuillaume** [comment]
ops forgot an import

**Comment by japgolly** [comment]
Hi @MasseGuillaume, sorry about the delay. 0.11.2 was already released. There's a new 0.11.3.md changelog. Can you please move the changelog comment to that file and we can merge.

**Comment by japgolly** [comment]
Done, thank you

**Pull request merged**
