### PR TITLE
Add references to diode and scalafiddle-editor in README

### PR DESCRIPTION
**Pull request by malaman**
Hi, 

thanks for package!
It is really cool, that so solid ecosystem already exists around scalajs-react.

For me [diode](https://github.com/suzaku-io/diode) and [scalafiddle-editor](https://github.com/scalafiddle/scalafiddle-editor) projects were very helpful for understanding how to build frontend apps with scalajs-react.
 
I've added references to the packages in README.

### CODE REVIEW

**Comment by japgolly** [comment]
Good idea, thanks! One little nit pick about Diode:

> library for managing immutable application state with unidirectional data flow

I'm not sure if just me but it seems to imply that unidirectional data flow isn't supported/possible out-of-the-box, where as it is. I think the more defining attribute Elm-style architectures is that the model/flow is global. As far as unidirectional data flow, React provides that out of the box in the micro, and I achieve it in the macro in a modular, composable fashion (as opposed to global) using optics and the `ext-monocle` scalajs-react module. Should we tweak the description? What do you think?

**Comment by malaman** [comment]
Thanks for feedback.
I will update PR tomorrow and remove unidirectional data flow texting from diode description.
Also I will add scalacenter/scastie to list of open source projects, which are using scalajs-react.

Global state management (flux/redux) is very popular in JS based React projects and I believe what people, which come from js side (like me) automatically start to look for something similar in scala.js.

Other ways of state management is not very known. 
I will look in ext-monocle approach and try to create another PR with the doc regarding possible options for state management.

**Comment by malaman** [comment]
PR is updated.

**Comment by japgolly** [comment]
LGTM, thanks a lot for this - it's a good idea to link to more of the ecosystem - and sorry about the delay

**Pull request merged**
