### PR TITLE
Support for JS Component Types.

### PR DESCRIPTION
**Pull request by imcharsi**
Hi.

As we talked at https://github.com/japgolly/scalajs-react/issues/157, I tried this pull request.

Review please.

### CODE REVIEW

**Comment by japgolly** [comment]
Hmmm interesting... I'm very happy that you supplied a proper test case for this :) Nice work.

@chandu0101 You seem to do a lot of work with JS React components. Do  you have any thoughts on this?

**Comment by chandu0101** [comment]
on a quick glance ,so end user have to write this code
```scala
React.createFactory(SampleReactComponent)(SampleReactComponentProperty(ref = ref, propOne = "123"))
```
to use custom component SampleReactComponent ? 
if its the case sorry i'll disagree with you  , for me the current facade way that we're using
https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/Addons.scala#L13
is more elegant , because end user using it like an API ,he'll pass inputs required (no need to worry about  props ,createFactory... )

**Comment by imcharsi** [comment]
Hi.

Thanks for your replies.

I understand that the API is something inconvenient, too.

For `React.createFactory`, we can write some codes like below with suggested API.

```
object Xxx {
  val Xxx = React.createFactory(SomeComponent)
}

import Xxx.Xxx

Xxx(SomeProperty(...))
```

By the way, with Scala-React-API, we use the API like below.

```
object Xxx {
  val Xxx = ReactComponentB[SomeProperty]("S")....build
}

import Xxx.Xxx

Xxx(SomeProperty(...))
```

At least, for API usage I don't think that there are any significantly different.

**Comment by chandu0101** [comment]
>At least, for API usage I don't think that there are any significantly different
agree , 
currently i am creating extra apply methods to overcome this for scala components

```scala
object GeoJsonFeatureFarm {

  val component = ReactComponentB[Props](..)
  case class Props(geojsonFeature: Option[GeoJsonFeature],index :Int, onAddUpdateSuccess : (GeoJsonFeature,Int) => Unit ,onCancel :() => Unit)

  def apply(geojsonFeature: Option[GeoJsonFeature],index : Int,onAddUpdateSuccess : (GeoJsonFeature,Int) => Unit ,onCancel : () => Unit = null , ref: js.UndefOr[String] = "", key: js.Any = {}) = component.set(key, ref)(Props(geojsonFeature,index,onAddUpdateSuccess,onCancel))

}
```
to get uniform styles all for all components!

my point is we don't need to follow existing scalajs-react API style 

in next version of scalajs-react ( that supports reactjs 0.14) will have a new API kind of similar to existing facade way.

>japgolly - In the next major release I'll probably lump all the big changing things together (components as classes, React 14, unify -->/==>/~~>)

that being said ignore me if you  prefer u r js world api , its always good to have more options people choose what they love :)

**Comment by imcharsi** [comment]
Hi.

Thanks for reply.

> my point is we don't need to follow existing scalajs-react API style.

Right.

> Its always good to have more options, people choose what they like :)

Yes. I hope so.

**Comment by japgolly** [comment]
@imcharsi Sorry to keep you waiting. Could you please make some changes:

1. The `Props` type in all the new JS traits should have an upper-bound of `js.Any`. Example, please replace `JSComponentType[Props,` with `JSComponentType[Props <: js.Any,`.
2. Please replace `JS` with `Js`, so `JSComponentType` becomes `JsComponentType`.
3. Could you please write a doc that:
  1. Summarises the types like in [TYPES.md](https://github.com/japgolly/scalajs-react/blob/master/doc/TYPES.md#components)
  2. Shows how to write a facade for, and use a JS component.
4. The JS types have `Props` but no `State`. They should have `State` too, no?

**Comment by imcharsi** [comment]
Hi.

I'm sorry for lately reply.

I'll try as you said.

Thanks.

**Comment by imcharsi** [comment]
Hi.

I tried as you said.

But, you may need to check correction about spell and grammar especially. I'm sorry about this.

Review please.

**Comment by japgolly** [comment]
@imcharsi I'm not going to give this a full review today because I have other work I need to get done, so there will probably be another delay. I want to quickly say, I had a skim just now (a quick look), and it looks great! So thank you very much! I'll get back to you soon.

**Comment by japgolly** [comment]
Hi @imcharsi. I just had a proper read though. It looks good to me, I'll merge it now. Big thank you for your effort and patience. I especially appeciate the doc and tests. :+1: :+1:

**Comment by japgolly** [comment]
@imcharsi FYI I made a few follow-up edits ↓, nearly all just tweaking the documentation. Thanks again.

https://github.com/japgolly/scalajs-react/compare/2b74e842...1f6de8d

**Pull request merged**
