### PR TITLE
Support changing <title> on route change 

### LINKED ISSUE #290: Support changing <title> on route change

### PR DESCRIPTION
**Pull request by ant8e**
Fixes #290

### CODE REVIEW

**Comment by japgolly** [comment]
Oh, cool, that was easy. The styles are a bit inconsistent but I'll fix that myself. I should add auto-formatting at some point.... Anyway, cheers, will merge.

**Comment by japgolly** [comment]
Ah crap. Next time please also just add a mention in the changelog. I forgot as well. :)

**Comment by japgolly** [comment]
@ant8e My mind was in slow-mode when I hit the merge button.
FYI I ended up making a few changes to your PR 0a6600be6b3cc0e6bce5cf872567461496897e0d :)

**Comment by ant8e** [comment]
Thanks,  your changes makes this thing better.
Sorry I was a bit in a hurry and forgot about the doc and changelog.

**Pull request merged**
