### PR TITLE
Unsfasespec

### PR DESCRIPTION
**Pull request by chandu0101**
addresses #132 

actually code is from @wav fork , looks like hes busy so just want to take a chance to help .. 

apart from #132 concerns ,its always better to have unsafe method (to allow end user what ever the hell he want to do ) , so that in future users don't need to wait for next version releases .

### CODE REVIEW

**Comment by japgolly** [comment]
Cool. Can you do the following:

1. Rename to `configureSpec`.
2. Align those colons on line 79.
3. On line 196, move the application of the function down. It should be the last thing called so that the fn receives the spec fully built instead of half built.
4. Squash ye commits.

**Comment by chandu0101** [comment]
i have no idea whats going on here ,let me know if its okay ?

**Comment by japgolly** [comment]
I got it: 5a76e382f03ca2c8124931112ed5e0c1878daf89

**Comment by chandu0101** [comment]
aww , thanks a lot mate :+1:

**Pull request closed without merging**
