### PR TITLE
Add Callback-integrated AJAX helper

### LINKED ISSUE #443: Add Callback-integrated AJAX helper
Builds on #442

### PR DESCRIPTION
**Pull request by japgolly**
Closes #443

### CODE REVIEW

**Comment by cquiroz** [comment]
This is going to be very useful 👍

**Comment by japgolly** [comment]
@cquiroz Yeah I always hoped somebody would just contribute this cos there was a lot of complaining about it's absence. Maybe I take for granted how easy FP is because I put in the work and time to learn it and was lucky enough to then use it everyday; I suspect it might've been daunting to others that didn't have that learning and experience so maybe that's why no one contributed? It's a shame cos I will happily mention anyone interested *(hint hint to anyone who reads this)*. But anyway, recently I needed this for the first time, so here it is.

**Comment by japgolly** [comment]
oh btw @cquiroz, don't think that I'm implying that you're complaining or anything like that. I would say that directly (and switch tact on) if so. I'm just speaking in generalities with literally no-one specific in mind :)

**Comment by cquiroz** [comment]
Don't worry. It didn't occur to me earlier that this would be useful or I'd have tried myself.
When I started with `scalajs-react` I had little exposure to FP and it seemed very alien, now that I'm more comfortable with the concepts I really appreciate the effort you've put in this library and being strict about purity.

I'd certainly be interested to contribute more, so just give a shoutout 😄

**Pull request merged**
