### PR TITLE
Import ReactTestUtils from react-addons-test-utils

### PR DESCRIPTION
**Pull request by chandu0101**
React team recommens to import addons explicitly.  https://facebook.github.io/react/docs/test-utils.html

### CODE REVIEW

**Comment by japgolly** [comment]
Erm, thanks but this didn't work. Travis CI broke big-time.

**Comment by chandu0101** [comment]
oh yeah have to update test deps!

**Comment by japgolly** [comment]
Ah, is it a new change in 15.1.0?

**Comment by chandu0101** [comment]
addons published as different packages since 0.14.x!

**Comment by japgolly** [comment]
no mention in changelogs

**Comment by japgolly** [comment]
Thanks but #320 will supersede this.

**Pull request closed without merging**
