### PR TITLE
Add Reusability#logNonReusable, addresses #421

### PR DESCRIPTION
**Pull request by SkyWriter**
Adds Reusability#logNonReusable wrapper to aid quick debugging.

### CODE REVIEW

**Comment by SkyWriter** [comment]
@japgolly hopefully I got your idea right :-)

**Comment by SkyWriter** [comment]
Wow, such a detailed feedback. Thank you for taking your time to walk me through.

I have a couple of notes/questions though:

- Just to explain my reasoning: I've deliberately placed `logNonReusable` into the object instead of the class. The class seemed to me very generic (all combinators and stuff), and method like this looked a little bit out of place. Anyways, I absolutely trust you to point out where it fits.

- How about making a title just a part of the format and not supplying it as a seprate argument? E.g. `fmt: (=> String, => String) => String = (x,y) => s"Non-reusability:\n- $x\n- $y"`.

**Comment by SkyWriter** [comment]
@japgolly Apart from my question, I think I did all the changes :+1: Once again, thanks for the review!

**Comment by japgolly** [comment]
No problem! In response to your questions:

1. My reasoning about class vs object is based on OO's message parsing roots, and/or how OO is implemented: (non-virtual) class methods have an implicit hidden parameter which is the class instance itself (aka `this`). Loosely speaking, I normally mentally partition method arguments into sets of mandatory and optional. If the mandatory set of args contains exactly one data type defined in the subject library/project, then I make it a class method, otherwise I make it an object method. Not just in terms of organisation but also it's also better in terms of call-site syntax. Although to reiterate, it's not a hard rule, there are cases in which other considerations exist that trump it, but it most often applies.

2. Yes, you're right that having just `fmt` instead of `title` and `fmt` is normally better practice. However there's a special use case I want to accommodate, I can imagine using this in a few places and specifying only the title, eg. `.logNonReusable(title = "Sidebar")` and `.logNonReusable(title = s"User ${user.id}")`. If users want to accomplish the same using only `fmt` you can imagine how tedious it becomes.

**Comment by SkyWriter** [comment]
> My reasoning about class vs object is based on OO's message parsing roots, and/or how OO is implemented...

Right, of course! With my FP experience coming from Haskell and being in a "functional mode" I pretty often tend to forget that Scala is a fully-blown OO language too, and OO practicies apply as well.

> However there's a special use case I want to accommodate, I can imagine using this in a few places and specifying only the title ... Can you please ... introduce a title arg.

Good thinking. I've introduced the `title` parameter.

> Can you please ... reintroduce def logNonReusable that simply calls logNonReusable(). The empty parens at the end usually represents side-effects in Scala conventions so I'd like to avoid it's need in downstream users' code.

Done!

**Pull request merged**
