### PR TITLE
Make Callback.when lazy

### PR DESCRIPTION
**Pull request by Daxten**
hey,
Callback.when should be evaluated lazily in my opinion, one example:

```scala
DifferentComponent(callback = Callback.when(dom.confirm("Really?"))(doSomething))
```

### CODE REVIEW

**Comment by Daxten** [comment]
I just saw how Callback.lazy is implemented and think my second commit would be a better fit for this.
I'm also interested in input if someone thinks this is a bad idea

**Comment by japgolly** [comment]
Hey. The problem with that is that you're mixing pure/impure code. `dom.confirm("Really?")` is impure and should be wrapped in `CallbackTo` (makes it reusable too). What do you think about one of these instead?

```scala
val prompt = CallbackTo(dom.confirm("Really?"))
prompt.flatMap(Callback.when(_)(doSomething)

// or better:
val prompt = CallbackTo(dom.confirm("Really?"))
prompt.flatMap(doSomething.when)

// or if there are newbies on the team
for {
  allow <- CallbackTo(dom.confirm("Really?"))
  _     <- doSomething.when(allow)
} yield ()
```

**Comment by Daxten** [comment]
yeah that looks better.. maybe there could be a 

```
def when(prop: CallbackTo[Boolean]): Callback
```

? Also after thinking about it my implementation wouldn't even fix my code :)

**Comment by japgolly** [comment]
We could overload it....
```
def when(cond: Boolean): Callback
def when(cond: CallbackTo[Boolean]): Callback
```

**Pull request closed without merging**
